apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: k61317qsh-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:f1189ea4a72a0e29c54af8ca7cd291f670cd9c83@sha256:7e8adad1b256536e54b01f684985f3a0ae2ccabec2507d0e12d162af7ad84136
          name: container-image
